#!/usr/bin/env bash
# landscape-capture.sh — Auto-capture AI landscape data to vault
set -euo pipefail

VAULT="$HOME/vault"
DATE=$(date -u +%Y-%m-%d)

echo "🔍 AI Landscape Capture — $DATE"

REPORT="$VAULT/Research/AI Landscape $DATE.md"
echo "# AI Landscape Scan — $DATE" > "$REPORT"
echo "" >> "$REPORT"
echo "Auto-generated by landscape-capture.sh" >> "$REPORT"
echo "" >> "$REPORT"

CATEGORIES=("agent orchestration" "memory management" "self improvement" "code review" "research" "knowledge graph" "prompt engineering")

for cat in "${CATEGORIES[@]}"; do
  echo "### $cat" >> "$REPORT"
  clawhub search "$cat" --limit 3 2>/dev/null >> "$REPORT" || echo "(search failed)" >> "$REPORT"
  echo "" >> "$REPORT"
  sleep 1
done

echo "## Installed Skills Status" >> "$REPORT"
echo "Total: $(ls ~/skills/ | wc -l)" >> "$REPORT"
echo "" >> "$REPORT"

echo "## Agent Roster" >> "$REPORT"
cat ~/.openclaw/openclaw.json 2>/dev/null | jq -r '.agents.list[].id' >> "$REPORT" 2>/dev/null
echo "" >> "$REPORT"

echo "📝 Report saved to: $REPORT"
