#!/usr/bin/env bash
# index.sh — regenerate INDEX.md from graph/, root docs, GLOSSARY, OPEN_QUESTIONS, howto.
# Pure python3, deterministic. Always overwrites.
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
python3 - <<'PY' > INDEX.md
import os, re

print("# Index")
print()
print("One-page lookup for every term, node, and doc in the transfer pack.")
print("Use this when you don't yet know what to search for.")
print()
print("> Generated by `scripts/index.sh` from `graph/nodes/`, `graph/edges/`,")
print("> root docs, `GLOSSARY.md`, `OPEN_QUESTIONS.md`, `howto/`. Do not edit by hand.")
print()

print("## Always read first")
print()
for d in ["README.md","MACBOOK_AGENT_HANDOFF_MASTER.md","SYSTEM_GRAPH.md",
          "AGENT_TRAVERSAL.md","AGENT_BOOTSTRAP.md","GLOSSARY.md",
          "OPEN_QUESTIONS.md","TIMELINE.md","CONTRIBUTING_TO_GRAPH.md",
          "05-fresh-context-project-app-model.md"]:
    if os.path.exists(d):
        line = ""
        for l in open(d).read().splitlines()[1:]:
            l = l.strip()
            if l and not l.startswith("#") and not l.startswith(">"):
                line = l[:160]; break
        print(f"- [`{d}`]({d}) — {line}")
print()

print("## Handoff series (long-form)")
print()
for d in sorted([f for f in os.listdir(".") if re.match(r'0\d-.+\.md$', f)]):
    line = ""
    for l in open(d).read().splitlines()[1:6]:
        l = l.strip("* ").strip()
        if l and not l.startswith("#") and not l.startswith(">"):
            line = l[:160]; break
    print(f"- [`{d}`]({d}) — {line}")
print()

print("## Nodes (by load priority)")
print()
ndir = "graph/nodes"
nodes = []
for fn in sorted(os.listdir(ndir)):
    if not fn.endswith(".qmd"): continue
    s = open(os.path.join(ndir,fn)).read()
    st = (re.search(r'^status: (\S+)', s, re.M) or [0,'?'])[1]
    lp = int((re.search(r'^load_priority: (\d+)', s, re.M) or [0,'9'])[1])
    era= (re.search(r'^era: (\S+)', s, re.M) or [0,'?'])[1]
    m = re.search(r'^---\n.*?\n---\n# .+?\n\n(.+?)(?:\n\n|$)', s, re.S)
    line = m.group(1).strip().split("\n")[0] if m else ""
    nodes.append((lp, fn[:-4], st, era, line))
nodes.sort()
last = None
for lp, n, st, era, line in nodes:
    if lp != last:
        print(f"\n### Priority {lp}\n")
        last = lp
    print(f"- [`{n}`](graph/nodes/{n}.qmd) — *{st} · {era}* · {line[:160]}")
print()

print("## Edge topics")
print()
edir = "graph/edges"
for fn in sorted(os.listdir(edir)):
    if not fn.endswith(".md"): continue
    p = os.path.join(edir,fn)
    rule = ""
    for l in open(p).read().splitlines():
        if l.strip().startswith("**Rule:**"):
            rule = l.strip().lstrip("*").strip(" *"); break
    print(f"- [`{fn[:-3]}`]({p}) — {rule}")
print()

print("## Glossary terms")
print()
g = open("GLOSSARY.md").read()
for m in re.finditer(r'^\| \*\*(.+?)\*\* \| (.+?) \|', g, re.M):
    print(f"- **{m.group(1)}** — {m.group(2)[:160]}")
print()

print("## Open questions")
print()
oq = open("OPEN_QUESTIONS.md").read()
for m in re.finditer(r'^## (Q\d+) — (.+?)$', oq, re.M):
    print(f"- {m.group(1)} — {m.group(2)}  ([OPEN_QUESTIONS.md](OPEN_QUESTIONS.md))")
print()

print("## How-to playbooks")
print()
hdir = "howto"
if os.path.isdir(hdir):
    for fn in sorted(os.listdir(hdir)):
        if not fn.endswith(".md") or fn == "README.md": continue
        line = ""
        for l in open(os.path.join(hdir,fn)).read().splitlines()[1:8]:
            l = l.strip()
            if l and not l.startswith("#") and not l.startswith(">"):
                line = l[:160]; break
        print(f"- [`howto/{fn}`](howto/{fn}) — {line}")
print()

print("## Scripts")
print()
for s,desc in [("scripts/probe.sh","detect Path A vs Path B for AGENT_BOOTSTRAP"),
               ("scripts/check-graph.sh","graph integrity check (warns, never blocks)"),
               ("scripts/manifest.sh","regenerate SYSTEM_MANIFEST.json"),
               ("scripts/index.sh","regenerate INDEX.md (this file)")]:
    print(f"- [`{s}`]({s}) — {desc}")
print()

print("## Inventory (provenance)")
print()
print("- [`lineage-index/inventory/GITHUB_REPOS.md`](https://github.com/TrajanWJ/ema-transfer-pack-20260422-060938/blob/lineage-index/inventory/GITHUB_REPOS.md) — TrajanWJ EMA-related GitHub repos")
print("- [`lineage-index/inventory/LOCAL_ROOTS.md`](https://github.com/TrajanWJ/ema-transfer-pack-20260422-060938/blob/lineage-index/inventory/LOCAL_ROOTS.md) — agent-vm/host paths")
print("- [`github-legacy-repos/REPOS.json`](https://github.com/TrajanWJ/ema-transfer-pack-20260422-060938/blob/github-legacy-repos/REPOS.json) — full repo inventory with metadata")
PY
echo "wrote INDEX.md ($(wc -l < INDEX.md) lines)"
